enum Enum_Attr {
	/**道具*/ITEM = 1,
	/**装备*/EQUIP,
	/**银两*/yinLiang,
	/**元宝*/yuanBao,
	/**绑定元宝*/bindYuanBao,
	/**等级*/LEVEL,
	/**经验*/EXP,
	/**帮会经验*/GANGEXP,
	/**帮贡*/BANGGONG,
	/**香火值*/XIANGHUOZHI,
	/**精铁*/JINGITE,
	/**玄铁*/XUANTIE,
	/**神铁*/SHENTIE,
	/**朱果*/ZHUGUO,
	/**蟠桃*/PANTAO,
	/**人参果*/RENSHENGUO,
	/**友情币 */FRIEND,
	/**功勋*/GONGXUN,
	/**威望 */WEIWANG,
	/**法宝 */FABAO,
	/**天下第一积分 */TX_SCORE,
	/** 当前生命*/HP = 101,
	/** 生命上限*/HP_MAX,
	/** 攻击力*/ATTACK,
	/** 防御*/DEFENSE,
	/** 攻速*/ATTACK_SPEED,
	/** 暴击率*/CRIT,
	/** 抵抗暴击率*/RESCRIT,
	/**暴伤增加 */CRIT_ADD,
	/**暴伤减免 */CRIT_REDUCE,
	/**伤害减少 */DMG_REDUCE_VALUE,
	/**伤害增加 */DMG_ADD_VALUE,
	/** PVP伤害减免*/PVP_DMG_REDUCE,
	/** PVP伤害加成*/PVP_DMG_ADD,
	/** 战力*/POWER,
	/** 无视防御*/DMG_ADD,
	/** 减免无视*/DMG_REDUCE,
	/**技能伤害 */SKILL_DMG_ADD,
	/**技能伤害值 */SKILL_DMG_VALUE,
	/**闪避 */ADV,
	/**命中 */HIT,
	/**金 */WXJIN,
	/**木 */WXMU,
	/**水*/WXSHUI,
	/**火*/WXHUO,
	/**土*/WXTU,
	/**PVE伤加*/PVE_DMG_ADD,
	/**PVE伤减*/PVE_DMG_REDUCE
}