var Enum_Attr;
(function (Enum_Attr) {
    /**道具*/ Enum_Attr[Enum_Attr["ITEM"] = 1] = "ITEM";
    /**装备*/ Enum_Attr[Enum_Attr["EQUIP"] = 2] = "EQUIP";
    /**银两*/ Enum_Attr[Enum_Attr["yinLiang"] = 3] = "yinLiang";
    /**元宝*/ Enum_Attr[Enum_Attr["yuanBao"] = 4] = "yuanBao";
    /**绑定元宝*/ Enum_Attr[Enum_Attr["bindYuanBao"] = 5] = "bindYuanBao";
    /**等级*/ Enum_Attr[Enum_Attr["LEVEL"] = 6] = "LEVEL";
    /**经验*/ Enum_Attr[Enum_Attr["EXP"] = 7] = "EXP";
    /**帮会经验*/ Enum_Attr[Enum_Attr["GANGEXP"] = 8] = "GANGEXP";
    /**帮贡*/ Enum_Attr[Enum_Attr["BANGGONG"] = 9] = "BANGGONG";
    /**香火值*/ Enum_Attr[Enum_Attr["XIANGHUOZHI"] = 10] = "XIANGHUOZHI";
    /**精铁*/ Enum_Attr[Enum_Attr["JINGITE"] = 11] = "JINGITE";
    /**玄铁*/ Enum_Attr[Enum_Attr["XUANTIE"] = 12] = "XUANTIE";
    /**神铁*/ Enum_Attr[Enum_Attr["SHENTIE"] = 13] = "SHENTIE";
    /**朱果*/ Enum_Attr[Enum_Attr["ZHUGUO"] = 14] = "ZHUGUO";
    /**蟠桃*/ Enum_Attr[Enum_Attr["PANTAO"] = 15] = "PANTAO";
    /**人参果*/ Enum_Attr[Enum_Attr["RENSHENGUO"] = 16] = "RENSHENGUO";
    /**友情币 */ Enum_Attr[Enum_Attr["FRIEND"] = 17] = "FRIEND";
    /**功勋*/ Enum_Attr[Enum_Attr["GONGXUN"] = 18] = "GONGXUN";
    /**威望 */ Enum_Attr[Enum_Attr["WEIWANG"] = 19] = "WEIWANG";
    /**法宝 */ Enum_Attr[Enum_Attr["FABAO"] = 20] = "FABAO";
    /**天下第一积分 */ Enum_Attr[Enum_Attr["TX_SCORE"] = 21] = "TX_SCORE";
    /** 当前生命*/ Enum_Attr[Enum_Attr["HP"] = 101] = "HP";
    /** 生命上限*/ Enum_Attr[Enum_Attr["HP_MAX"] = 102] = "HP_MAX";
    /** 攻击力*/ Enum_Attr[Enum_Attr["ATTACK"] = 103] = "ATTACK";
    /** 防御*/ Enum_Attr[Enum_Attr["DEFENSE"] = 104] = "DEFENSE";
    /** 攻速*/ Enum_Attr[Enum_Attr["ATTACK_SPEED"] = 105] = "ATTACK_SPEED";
    /** 暴击率*/ Enum_Attr[Enum_Attr["CRIT"] = 106] = "CRIT";
    /** 抵抗暴击率*/ Enum_Attr[Enum_Attr["RESCRIT"] = 107] = "RESCRIT";
    /**暴伤增加 */ Enum_Attr[Enum_Attr["CRIT_ADD"] = 108] = "CRIT_ADD";
    /**暴伤减免 */ Enum_Attr[Enum_Attr["CRIT_REDUCE"] = 109] = "CRIT_REDUCE";
    /**伤害减少 */ Enum_Attr[Enum_Attr["DMG_REDUCE_VALUE"] = 110] = "DMG_REDUCE_VALUE";
    /**伤害增加 */ Enum_Attr[Enum_Attr["DMG_ADD_VALUE"] = 111] = "DMG_ADD_VALUE";
    /** PVP伤害减免*/ Enum_Attr[Enum_Attr["PVP_DMG_REDUCE"] = 112] = "PVP_DMG_REDUCE";
    /** PVP伤害加成*/ Enum_Attr[Enum_Attr["PVP_DMG_ADD"] = 113] = "PVP_DMG_ADD";
    /** 战力*/ Enum_Attr[Enum_Attr["POWER"] = 114] = "POWER";
    /** 无视防御*/ Enum_Attr[Enum_Attr["DMG_ADD"] = 115] = "DMG_ADD";
    /** 减免无视*/ Enum_Attr[Enum_Attr["DMG_REDUCE"] = 116] = "DMG_REDUCE";
    /**技能伤害 */ Enum_Attr[Enum_Attr["SKILL_DMG_ADD"] = 117] = "SKILL_DMG_ADD";
    /**技能伤害值 */ Enum_Attr[Enum_Attr["SKILL_DMG_VALUE"] = 118] = "SKILL_DMG_VALUE";
    /**闪避 */ Enum_Attr[Enum_Attr["ADV"] = 119] = "ADV";
    /**命中 */ Enum_Attr[Enum_Attr["HIT"] = 120] = "HIT";
    /**金 */ Enum_Attr[Enum_Attr["WXJIN"] = 121] = "WXJIN";
    /**木 */ Enum_Attr[Enum_Attr["WXMU"] = 122] = "WXMU";
    /**水*/ Enum_Attr[Enum_Attr["WXSHUI"] = 123] = "WXSHUI";
    /**火*/ Enum_Attr[Enum_Attr["WXHUO"] = 124] = "WXHUO";
    /**土*/ Enum_Attr[Enum_Attr["WXTU"] = 125] = "WXTU";
    /**PVE伤加*/ Enum_Attr[Enum_Attr["PVE_DMG_ADD"] = 126] = "PVE_DMG_ADD";
    /**PVE伤减*/ Enum_Attr[Enum_Attr["PVE_DMG_REDUCE"] = 127] = "PVE_DMG_REDUCE";
})(Enum_Attr || (Enum_Attr = {}));
//# sourceMappingURL=Enum_Attr.js.map